#!/usr/bin/env python3
"""Check the reviewed Go dependency policy and generate shipped legal notices."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import tarfile

ROOT = Path(__file__).resolve().parent.parent
LEGAL_FILES = ("LICENSE", "NOTICE", "licenses/THIRD_PARTY_NOTICES.txt")
LEGAL_NAME = re.compile(r"^(LICENSE|LICENCE|COPYING|NOTICE|PATENTS)([._-].*)?$", re.I)


def go(*args):
    # A sibling workspace or local replacement must not conceal published deps.
    return subprocess.check_output(
        ["go", *args], cwd=ROOT, text=True,
        env=dict(os.environ, GOWORK="off", GOFLAGS="-mod=readonly"),
    )


def json_stream(text):
    decoder = json.JSONDecoder()
    while text.strip():
        value, end = decoder.raw_decode(text.lstrip())
        yield value
        text = text.lstrip()[end:]


def checked_text(path, expected):
    data = path.read_bytes()
    if hashlib.sha256(data).hexdigest() != expected:
        raise ValueError(f"legal text changed; review the policy before updating: {path}")
    return data.decode("utf-8").rstrip() + "\n"


def generate():
    policy = json.loads((ROOT / "licenses/policy.json").read_text())
    checked_text(ROOT / "LICENSE", policy["project_license_sha256"])
    if not (ROOT / "NOTICE").read_text().strip():
        raise ValueError("project NOTICE must not be empty")
    module_file = json.loads(go("mod", "edit", "-json"))
    if module_file.get("Replace"):
        raise ValueError("license checks require published dependencies without replace directives")
    if module_file["Go"] != policy["go_version"] or go("env", "GOVERSION").strip() != "go" + policy["go_version"]:
        raise ValueError("Go version changed; review runtime notices and update licenses/policy.json")
    modules = list(json_stream(go("list", "-m", "-json", "all")))
    dependencies = {m["Path"]: m for m in modules if not m.get("Main")}
    if set(dependencies) != set(policy["modules"]):
        missing = sorted(set(dependencies) - set(policy["modules"]))
        stale = sorted(set(policy["modules"]) - set(dependencies))
        raise ValueError(f"dependency license review required; unreviewed={missing}, removed={stale}")
    sections = [
        "THIRD-PARTY NOTICES\n\n"
        "Generated by python3 scripts/licenses.py --write. Do not edit by hand.\n"
        "Project terms are in LICENSE and NOTICE. Dependencies retain their own terms.\n"
        "This report covers the complete selected Go module graph (all platforms),\n"
        "plus the reviewed Go runtime and Unicode data notices. External agent CLIs,\n"
        "Node.js and Python interpreters are installed separately and are not bundled.\n"
    ]
    for name, module in sorted(dependencies.items()):
        review = policy["modules"][name]
        if module.get("Replace") or module["Version"] != review["version"]:
            raise ValueError(f"dependency version changed; review licenses for {name}")
        downloaded = json.loads(go("mod", "download", "-json", name + "@" + module["Version"]))
        directory = Path(downloaded["Dir"])
        legal_paths = {p.relative_to(directory).as_posix() for p in directory.rglob("*")
                       if p.is_file() and LEGAL_NAME.fullmatch(p.name)}
        if legal_paths != set(review["files"]):
            raise ValueError(f"legal file inventory changed; review licenses for {name}")
        sections.append(f"{name} {module['Version']}\nLicense: {review['license']}\nSource: {review['source']}\n")
        for filename, checksum in sorted(review["files"].items()):
            sections.append(f"--- {name}/{filename} ---\n\n" + checked_text(directory / filename, checksum))
    if dependencies:
        go("mod", "verify")
    for review in policy["supplemental"]:
        sections.append(f"{review['title']}\nSource: {review['source']}\n\n"
                        + checked_text(ROOT / review["file"], review["sha256"]))
    return ("\n" + "=" * 78 + "\n\n").join(sections)


def check(write=False):
    report = ROOT / "licenses/THIRD_PARTY_NOTICES.txt"
    expected = generate().encode("utf-8")
    if write:
        report.write_bytes(expected)
    elif not report.exists() or report.read_bytes() != expected:
        raise ValueError("third-party notices are stale; run python3 scripts/licenses.py --write")


def legal_files():
    """The same reviewed files accompany every native and installer package."""
    return {name: (ROOT / name).read_bytes() for name in LEGAL_FILES}


def check_npm(path):
    with tarfile.open(path, "r:gz") as archive:
        for filename, expected in legal_files().items():
            name = "package/" + filename
            matches = [m for m in archive.getmembers() if m.name == name]
            if len(matches) != 1 or not matches[0].isfile() or archive.extractfile(matches[0]).read() != expected:
                raise ValueError(f"npm package has missing or altered legal text: {filename}")
        metadata = json.load(archive.extractfile("package/package.json"))
        if metadata.get("license") != "Apache-2.0":
            raise ValueError("npm package must declare Apache-2.0")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate notices after policy review")
    args = parser.parse_args()
    try:
        check(args.write)
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        parser.exit(1, f"License check failed: {error}\n")
    print("Dependency license policy and third-party notices are current.")
